### PR TITLE
Embedding Images and Video

### PR DESCRIPTION
**Pull request by ishanchawla1**
This page is clone of youtube page. All the elements here are designed for a Microverse project and are not meant for commercial use.

### CODE REVIEW

**Comment by davidmrtz-dev** [comment]
Pull Request under review by  **[TSE] David Elí**. 👨‍💻

**Comment by davidmrtz-dev** [comment]
### **Status: Changes required.** 🛑 👀 🔍 
### Hi Team. 😄 
### Very good job so far, but we have a couple of issues to solve before move on. 💯 👍 
*****

- [ ] **Info video section.**

Let's check the section where the subscribe button is. This is how it looks now. ⬇️ 👀 

Screen Shot 2020-02-20 at 6 11 42 PM

This is how it should look ⬇️ 

Screen Shot 2020-02-20 at 6 12 01 PM
*****

*****
- [ ] **Style footer section.**

Kindly style the footer section to like the example youtube page, heres a screenshot. 😄 

Screen Shot 2020-02-20 at 6 13 54 PM

*****

*****

- [ ] **Implementation details**

Remember Team, we are working on making a clone, so keep eyes on the details 💯 

Add the comments section, you can follow the example below!
Screen Shot 2020-02-20 at 6 12 14 PM


*****

*****
Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).

- [ ] As shown in the lesson above, kindly make descriptive pull requests.

*****
Please make the changes required and submit a new code review once you are ready! 🙏 😃 

*****
### **Important note!** ☢️ ❗️ 
**In future projects, I am asking you not to close the pull request after the first review. You can make commits and submit new review requests using the same pull request.** 
*****

Happy coding! 😄 💻 

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your did a good job so far :+1: 

Here are thing you still need to change, before this project can be approved:

* [ ] Project name in README.md file should display your actual project name. Instead of image you have there right now, please use screenshot of your actual project or remove it at all.
* [ ] `Share` and `Subscribe` should be buttons, right now you have just images there.
* [ ]  Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
